name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install protoc
      uses: Arduino/actions/setup-protoc@master
      with:
        version: '3.x'

    - name: Get dependencies
      run: bash scripts/protoc-install.sh
        
    - name: Generate
      run: make generate

    - name: Build
      run: make build

    - name: Test
      run: make test
