name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Export GOPATH, GOBIN
      run: |
        mkdir -p $HOME/go
        echo ::set-env name=GOPATH::$HOME/go
        echo ::set-env name=GOBIN::$HOME/go/bin

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v2
      with:
        path: "service-template-grpc"
    
    - uses: bufbuild/buf-setup-action@v0.1.0
      with:
        version: '0.41.0' # The version of buf to download and use.

    - name: Get dependencies
      run: |
        go install \
          github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
          github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
          google.golang.org/protobuf/cmd/protoc-gen-go \
          google.golang.org/grpc/cmd/protoc-gen-go-grpc

    - name: Generate
      run: make generate

    - name: Build
      run: make build

    - name: Test
      run: make test
